### ISSUE TITLE
Getting access to gymKit

### ISSUE THREAD

**Issue by hayschan** [kormax/apple-gymkit#1]
> Bluetooth, ANT+ and Apple GymKit qualified

Buying a North Pole Engineering chip seems to make you access to gymKit. Do you think that is true? 

Here is the link: https://npe.fit/pages/oem-product-decision-guide

![image](https://github.com/kormax/apple-gymkit/assets/25737801/05330484-7c80-4743-9e64-e694165ac4dd)

**Comment by kormax** [comment]
Even if you manage to buy a chip, GymKit documentation & support will be a subject to NDA + business agreement, so It's a no-go (because when you sign these agreements, you are already forbidden from publishing anything, even if a person once had an ability read the documentation and does not have any more access to it now, they are considered "contaminated", meaning that they cannot perform reverse-engineering because it would be really hard to prove that special knowledge wasn't used).

For proper reverse-engineering & protocol analysis, one has to purchase pre-built equipment with the certified hardware, and sniff the BLE protocol, do other stuff to the hardware in order to retrieve more details. I see no other "proper" way around it.

**Comment by hayschan** [comment]
> For proper reverse-engineering & protocol analysis, one has to purchase pre-built equipment with the certified hardware, and sniff the BLE protocol, do other stuff to the hardware in order to retrieve more details. I see no other "proper" way around it.

The difficulty for getting a certified device is extremely high 😢 . I seldom see devices with GymKit pre-built. Most of them are probably in the fitness centers in the US. 

> Further research after that might require one to have real hardware samples in order to look at BLE communication and find out what data needs to be sent and received.

Did you manage to access one eventually?

**Comment by kormax** [comment]
No, I wasn't able to access one as they are very expensive. Otherwise I would have already published my findings.
